### ISSUE TITLE
Fatal Error on Sale Badge

### ISSUE THREAD

**Issue by chizdamasii** [CrocoBlock/suggestions#2947]
**1) Add a sale badge on a product listing
2) Use the %percentage_sale% macros  and save.
3) Go to preview, a fatal error will occur:**

`Fatal error: Uncaught Error: Call to a member function get_type() on null in /public_html/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php:62 Stack trace: 
#0 /public_html/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php(175): Jet_Woo_Builder_Macros->get_percentage_sale(NULL, false) 
#1 [internal function]: Jet_Woo_Builder_Macros->{closure}(Array) 
#2 /public_html/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php(177): preg_replace_callback('/%([a-z_-]+)(\\|...', Object(Closure), '-%percentage_sa...') 
#3 /public_html/wp-content/plugins/jet-woo-builder/includes/widgets/archive-product/jet-woo-builder-archive-sale-badge.php(197): Jet_Woo_Builder_Macros->do_macros('-%percentage_sa...') 
#4 /public_html/wp-content/plugins/jet-woo-builder/includes/widgets/archive-product/jet-woo-builder-archive-sale-badge.php(220): Elementor\Jet_Woo_Builder_Archive_Sale_Badge::render_callback(Array) 
#5 /hom in /public_html/wp-content/plugins/jet-woo-builder/includes/class-jet-woo-builder-macros.php on line 62
`

**Comment by chizdamasii** [comment]
**Note: The error occurs only in preview, and i understand why, but a null check should be in the code to avoid the error.**
