### ISSUE TITLE
Jet Woo Builder - Fatal Error when WooCommerce PDF Product Vouchers by SkyVerge is active.

### ISSUE THREAD

**Issue by joelcrump** [CrocoBlock/suggestions#5605]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
When both the WooCommerce PDF Product Vouchers plugin and the Jet Woo Builder plugin are active it causes a fatal error when trying to create a Woo Page Builder template. (see Screenshots)

**To Reproduce**
1. Go to 'Crocoblock>Woo Page Builder>Create New Template'
2. Fill out settings and load the builder.
3. See error:
<img width="1182" alt="Screen Shot 2022-07-07 at 2 40 41 PM" src="https://user-images.githubusercontent.com/52061064/177691871-0d6bb8df-aaae-44b4-b1b0-8dfd86d1aec6.png">
I believe this is because the only product in my store is a voucher so the Woo Page Builder isn't set up to use voucher products as previews for the builder? This is totally fine if you want to leave it this way but I thought it's worth reporting as this is a very popular plugin.

**Expected behavior**
Would be nice to have it compatible with voucher products from SkyVerge's WooCommerce PDF Product Vouchers plugin.

**Screenshots**
<img width="1182" alt="Screen Shot 2022-07-07 at 2 40 41 PM" src="https://user-images.githubusercontent.com/52061064/177691871-0d6bb8df-aaae-44b4-b1b0-8dfd86d1aec6.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 103.0.5060.53 (Official Build) (x86_64)

** Snippet from Error Log**
[Thu Jul 07 00:04:16.784535 2022] [proxy_fcgi:error] [pid xxxxxx:tid xxxxxxxxxxxxx] [client xxx.xxx.xxx.xx:x] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined function wc_pdf_product_vouchers_render_product_voucher_fields() in /home/xxxxxxxxxxxxxx/public_html/wp-content/plugins/woocommerce-pdf-product-vouchers/src/class-wc-pdf-product-vouchers-product.php:60\nStack trace:\n#0 /home/xxxxxxxxxxxxxx/public_html/wp-includes/class-wp-hook.php(307): WC_PDF_Product_Vouchers_Product->render_product_voucher_options()\n#1 /home/xxxxxxxxxxxxxx/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()\n#2 /home/xxxxxxxxxxxxxx/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()\n#3 /home/xxxxxxxxxxxxxx/public_html/wp-content/plugins/woocommerce/templates/single-product/add-to-cart/variation-add-to-cart-button.php(15): do_action()\n#4 /home/xxxxxxxxxxxxxx/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home/xxxxxx.cl......', referer: https://xxxxxxxxxxxxxx/wp-admin/edit.php?post_type=jet-woo-builder

**Comment by joelcrump** [comment]
This is also the case with Elementor by the looks, I've left a feature request on elementor's GitHub as this my automatically fix your conflict.
