### ISSUE TITLE
 Jetformbuilder reject Jetengine form legacy [conflict edit post]⚡

### ISSUE THREAD

**Issue by nreljed** [CrocoBlock/suggestions#5668]
![Plan de travail – 5](https://user-images.githubusercontent.com/82481592/180132876-e74f3173-6525-42f3-a804-5ef097dcb43c.png)

I transferred more than 200 posts posted using jetengine forms from my site1 to site2

on site2 I reproduced identically the forms of jetengine site1
with jetformbuilder + the dynamic link edit post

on site2 when I click edit on one of the 200 posts transferred, a strange fatal error is displayed

> Warning: explode() expects parameter 2 to be string, array given in C:\laragon\www\beta\wp-content\plugins\jetformbuilder\includes\blocks\types\media-field.php on line 57
> 
> Fatal error: Uncaught TypeError: Return value of Jet_Form_Builder\Blocks\Types\Media_Field::parse_preset() must be of the type array, null returned in C:\laragon\www\beta\wp-content\plugins\jetformbuilder\includes\blocks\types\media-field.php:57 Stack trace: #0 C:\laragon\www\beta\wp-content\plugins\jetformbuilder\includes\blocks\types\media-field.php(69): Jet_Form_Builder\Blocks\Types\Media_Field->parse_preset(Array) #1 C:\laragon\www\beta\wp-content\plugins\jetformbuilder\includes\blocks\types\base.php(266): Jet_Form_Builder\Blocks\Types\Media_Field->get_default_from_preset() #2 C:\laragon\www\beta\wp-content\plugins\jetformbuilder\includes\blocks\types\base.php(217): Jet_Form_Builder\Blocks\Types\Base->set_preset() #3 C:\laragon\www\beta\wp-content\plugins\jetformbuilder\includes\blocks\types\base.php(198): Jet_Form_Builder\Blocks\Types\Base->render_field(Array, '', Object(WP_Block)) #4 [internal function]: Jet_Form_Builder\Blocks\Types\Base->render_callback_field(Array, '', Object(WP_Block)) #5 C:\laragon\www\beta\wp- in C:\laragon\www\beta\wp-content\plugins\jetformbuilder\includes\blocks\types\media-field.php on line 57
> There has been a critical error on this website.

I exported the forms from jetengine site1 to site2 and activated "forms legacy" and imported my form edit and new , 
I changed the necessary parameters to put them in place and I click on edit 
now I can edit my posts not errors..

it is not possible to edit jetengine form legacy posts with jetformbuilder?
I don't understand where the problem is
staying on legacy forms is not a good idea
not being able to edit my posts with jetformbuilder either

**Comment by Crocoblock** [comment]
was fixed

If you have some other questions or still have this error, please get in touch with our support team https://crocoblock.com/help-center
