### ISSUE TITLE
Crashed (White Page) when adding custom post data

### ISSUE THREAD

**Issue by unitedonline** [CrocoBlock/suggestions#5881]
I'm not really sure how or why it happened but after creating a Custom Post Type and having added meta fields, when I tried adding via 'Add New' I got a blank page. I am able to add data through a form I've created via JetFormManager.

I have also received the following error message via email:

 WordPress Version 6.0.2
Active Theme: Hello Elementor (Version 2.6.1)
Plugin: JetEngine (Version 3.0.3.1)
Version PHP 8.0.23

ERROR
===========================================
E_ERROR in line 131 of the file 
/wp-content/plugins/jet-engine/framework/interface-builder/inc/controls/repeater.php. 

Error Code: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /wp-content/plugins/jet-engine/framework/interface-builder/inc/controls/repeater.php:131

Stack trace:
#0 /wp-content/plugins/jet-engine/framework/interface-builder/cherry-x-interface-builder.php(512): CX_Control_Repeater->render()

#1 /wp-content/plugins/jet-engine/framework/interface-builder/cherry-x-interface-builder.php(424): CX_Interface_Builder->build(Array)

#2 /wp-content/plugins/jet-engine/framework/post-meta/cherry-x-post-meta.php(288): CX_Interface_Builder->render()
#3 /wp-admin/includes/template.php(1401): Cherry_X_Post_Meta->render_metabox(Object(WP_Post), Array)
#4 /wp-admin/includes/post.php(2303): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#5 /wp-admin/edit-form-blocks.php(314): the_block_editor_meta_boxes()
#6 /wp-admin/post.php(187): require('/home1/uolbz/pu...')
#7 {main}
  thrown
  
  I'm attaching an exported skin
  
Thank you
[Pelates-Custom-Post-Types-skin-export-4.zip](https://github.com/Crocoblock/suggestions/files/9541916/Pelates-Custom-Post-Types-skin-export-4.zip)

**Comment by unitedonline** [comment]
I deleted a repeater CPT and re-created it and now it works fine.
