### ISSUE TITLE
Ajax JetSearch on custom field causes error on Php 8.0

### ISSUE THREAD

**Issue by Ezyweb-uk** [CrocoBlock/suggestions#7115]
JetSearch ajax works ok when the searching a custom post type on Php 8.0, but for another JetSearch on a custom fields the ajax causes an error. When Php is returned to v7.4 the error no longer occurs. In Firefox Inspector the ajax call returns error 500 and the debug log file includes the following message (file paths shortened for privacy):

`[22-Sep-2023 12:46:49 UTC] PHP Fatal error:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given in ..../wp-includes/shortcodes.php:628
Stack trace:
#0 ..../wp-includes/shortcodes.php(628): strpos(Array, '[')
#1 ...../wp-content/plugins/jet-search/includes/template-functions.php(113): strip_shortcodes(Array)
#2 ..../wp-content/plugins/jet-search/includes/rest-api/endpoints/search-route.php(136): Jet_Search_Template_Functions::get_post_content(Array, Object(WP_Post))
#3 .../wp-includes/rest-api/class-wp-rest-server.php(1181): Jet_Search_Rest_Search_Route->callback(Object(WP_REST_Request))
#4 ..../wp-includes/rest-api/class-wp-rest-server.php(1028): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/jet-search/v1/...', Array, NULL)
#5 ...../wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch(Object(WP_REST_Request))
#6 ...../wp-includes/rest-api.php(410): WP_REST_Server->serve_request('/jet-search/v1/...')
#7 ...../wp-includes/class-wp-hook.php(308): rest_api_loaded(Object(WP))
#8 ....../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#9 ...../wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#10 ...../wp-includes/class-wp.php(399): do_action_ref_array('parse_request', Array)
#11 ...../wp-includes/class-wp.php(780): WP->parse_request('')
#12 ...../wp-includes/functions.php(1334): WP->main('')
#13 ...../wp-blog-header.php(16): wp()
#14 ....../index.php(17): require('/......./......./...')
#15 {main}
  thrown in ......./wp-includes/shortcodes.php `

The above error occurs after entering a search term in the JetSearch box. Website details are in support ticket #157479

The ajax should return a list of products in a dropdown below, but instead return the default error message "Sorry, but we cannot handle your search query now. Please, try again later!"

A screenshot of the Inspector error 500 has been supplied in ticket #157479

 - OS: AlmaLinux
 - Web server: LiteSpeed
 - Browser: FireFox

Similar to [issue #6638](https://github.com/Crocoblock/suggestions/issues/6638)

**Comment by Ezyweb-uk** [comment]
Crocoblock Support were very helpful and discovered the JetSearch Results Area Post Content Source needed changing from 'Custom Field' to 'Post Content'. Once the Source was changed and the repeater custom field id was added to Custom Fields > Meta Fields List, the search then worked correctly, and with Php 8.0.

To display the repeater custom field data we added the following code provided by Support to the child theme functions.php file:

```
add_filter( 'jet-search/template/pre-get-meta-field', function($value, $meta, $post){
      $repeater_name    = 'repeater-name-id';
      $repeater_field    = 'repeater-field-id';
      $meta_key        = $meta['meta_key'] ?? '';
  
      if( $meta_key !== $repeater_name ){
          return $value;
      }
  
      $meta_value    = get_post_meta( $post->ID, $meta_key);
      $result        = array();
  
      foreach( $meta_value[0] as $k => $v){
          $result[] = $v[$repeater_field];
      }
  
      return array( implode(', ', $result) );
  
  }, 10, 3);
```
